### ISSUE TITLE
Some symbols are split into different syntax groups

### ISSUE THREAD

**Issue by tobia** [b123400/purescript-ide-sublime#5]
Many of us enjoy using the recent fonts that render common multi-character symbols as a single glyph, such as [Fira Code](https://github.com/tonsky/FiraCode)

But the current syntax definition seems to split some of the operators into different syntax groups, which prevents the font from doing its job.

Compare this piece of (nonsensical) PureScript code, rendered using the Haskell syntax definition (Ctrl-Shift-P, Set Syntax: Haskell):

![purescript code with haskell syntax definition](https://user-images.githubusercontent.com/48756/34358320-04b87c08-ea4f-11e7-9a62-e9162a9780a1.png)

with the same piece of code, using the PureScript syntax:

![purescript syntax definition](https://user-images.githubusercontent.com/48756/34358365-47890430-ea4f-11e7-9643-187cadad22d1.png)

Some of the operators are identified as a single syntax group and are rendered correctly by the font, while many others are not.

**Comment by b123400** [comment]
Confirmed. The syntax definition is inherited from another repo, which I didn't fully scan the codes. Let me fix it :)
